---
- name: configure web server
  hosts: servera.lab.example.com

  tasks:
    - name: Import the environment task file and set the variables
      import_tasks: tasks/environment.yml
      vars:
        package: httpd
        service: httpd
    - name: Import the firewall task file and set the variables
      import_tasks:  tasks/firewall.yml
      vars:
        firewall_pkg: firewalld
        firewall_svc: firewalld
        rule: http
    - name: Import the placeholder task file and set the vaiables
      import_tasks: tasks/placeholder.yml
      vars:
        file: /var/www/html/index.html

- name: Import test play file and set the variables
  import_playbook: plays/test.yml
  vars:
    url: 'http://servera.lab.example.com'
